version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    open-pull-requests-limit: 0
    groups:
      vulnerability-updates:
        dependency-type: "production"
        applies-to: security-updates
        update-types:
          - "patch"
          - "minor"
